@startuml

title CRC Example: Meta und Deployment 

object argocd_crc.yaml
argocd_crc.yaml : type = yaml
argocd_crc.yaml : kind = argo_app
argocd_crc.yaml : repo = manuela-gitops 
argocd_crc.yaml : sourcepath = deployment/execenv-crc
argocd_crc.yaml : namespace = argocd
argocd_crc.yaml : path = meta

object execenv_crc
execenv_crc : type = dir
execenv_crc : path = deployment

argocd_crc.yaml o-- execenv_crc


object line_dashboard_application.yaml.ln
line_dashboard_application.yaml.ln : type = link

object machine_sensor_application.yaml.ln
machine_sensor_application.yaml.ln : type = link

object messaging_application.yaml.ln
messaging_application.yaml.ln : type = link 

execenv_crc o-- line_dashboard_application.yaml.ln
execenv_crc o-- machine_sensor_application.yaml.ln
execenv_crc o-- messaging_application.yaml.ln

object line_dashboard_application.yaml
line_dashboard_application.yaml : type = yaml
line_dashboard_application.yaml : kind = argo_app

object machine_sensor_application.yaml
machine_sensor_application.yaml : type = yaml
machine_sensor_application.yaml : kind = argo_app

object messaging_application.yaml
messaging_application.yaml : type = yaml
messaging_application.yaml : kind = argo_app

line_dashboard_application.yaml.ln *-- line_dashboard_application.yaml
machine_sensor_application.yaml.ln *-- machine_sensor_application.yaml
messaging_application.yaml.ln *-- messaging_application.yaml


object instances
instances : type = dir
instances : path = config

object manuela_crc
manuela_crc : type = dir
manuela_crc : path = config/instances
instances o-- manuela_crc : subdir



manuela_crc o-- line_dashboard_application.yaml
manuela_crc o-- machine_sensor_application.yaml
manuela_crc o-- messaging_application.yaml


@enduml
