@startuml
namespace Git {
    note "Digital Twin\nDefines desired state\nTracks changes across time" as notedigitaltwin
    'Git.ConfigurationData .up. notedigitaltwin
    'Git.DeploymentData .left. notedigitaltwin

    abstract class GitRepository
    GitRepository : String gitURL

    namespace DeploymentData <<Database>> {
        class K8sComponentDeployment <<symlink>>
        K8sComponentDeployment : String directoryLocation


        class StandaloneComponentDeployment <<Kustomize Manifest>>
        note bottom of StandaloneComponentDeployment: currently not used/in scope

        abstract class ComponentDeployment

        class FirewallRule <<symlink>>
        FirewallRule : String directoryLocation

        class ExecutionEnvironment <<Directory>>
        ExecutionEnvironment : String path

        class NetworkPath <<Directory>>
        NetworkPath : String path

        class GitDeploymentRepository

        K8sComponentDeployment --|> ComponentDeployment
        StandaloneComponentDeployment --|> ComponentDeployment

        ComponentDeployment --o ExecutionEnvironment 
        ExecutionEnvironment --o GitDeploymentRepository 

        FirewallRule --o NetworkPath
        NetworkPath --o GitDeploymentRepository
    } 

    namespace ConfigurationData <<Database>> {
        class ComponentConfiguration <<Subdirectory>>
        ComponentConfiguration : Kustomize manifests
        ComponentConfiguration : GitLocation[] baseConfiguration
        ComponentConfiguration --> ComponentConfiguration : base >

        class Namespace <<k8s manifest>>
        Namespace : String name

        class ProvidedInterface <<Service or Route/Ingress>>
        ProvidedInterface : String hostname
        ProvidedInterface : String port

        class ConsumedInterface <<ConfigMap>>
        ConsumedInterface : String hostname
        ConsumedInterface : String port
        ConsumedInterface : boolean tlssni

        note top of ConsumedInterface: mounted to individual file under\n/etc/components/<componentname>/
        note "port are integers but ConfigMaps prefer Strings" as noteintasstring
        noteintasstring -- ConsumedInterface 
        noteintasstring -- ProvidedInterface

        class GitOpsCompatibleSecret <<Encrypted or KMS Reference>>

        class K8sComponentDeployment <<ArgoCD Application>>
        K8sComponentDeployment : String namespace
        K8sComponentDeployment : GitLocation componentConfiguration

        class FirewallRule <<k8s CustomResource>>

        class ApplicationInstanceOrTemplate <<Directory>>
        ApplicationInstanceOrTemplate : String path

        class GitConfigurationRepository

        ComponentConfiguration --o ApplicationInstanceOrTemplate 
        FirewallRule --o ApplicationInstanceOrTemplate
        
        K8sComponentDeployment --o ComponentConfiguration 
        "Namespace" --o ComponentConfiguration
        GitOpsCompatibleSecret --o ComponentConfiguration 
        ProvidedInterface --o ComponentConfiguration
        ConsumedInterface --o ComponentConfiguration

        GitOpsCompatibleSecret --o ApplicationInstanceOrTemplate 
        ApplicationInstanceOrTemplate --o GitConfigurationRepository

        K8sComponentDeployment -- Namespace : points to >


'        note "these are deployment specific -\nshouldn't they be deployment data?" as notedeploymentspecific
'        notedeploymentspecific -- ConsumedInterface
'        notedeploymentspecific -- ProvidedInterface

    }

    Git.DeploymentData.GitDeploymentRepository --|> GitRepository 
    Git.ConfigurationData.GitConfigurationRepository --|> GitRepository
'    Git.DeploymentData.ComponentDeployment -- Git.ConfigurationData.ComponentConfiguration : points to >
    Git.DeploymentData.FirewallRule -- Git.ConfigurationData.FirewallRule : points to >

    Git.DeploymentData.K8sComponentDeployment -- Git.ConfigurationData.K8sComponentDeployment : points to >

}
@enduml
