@startuml
namespace Git {
    note "Digital Twin\nDefines desired state\nTracks changes across time" as notedigitaltwin
    'Git.ConfigurationData .up. notedigitaltwin
    'Git.DeploymentData .left. notedigitaltwin

    abstract class GitRepository
    GitRepository : String gitURL

    namespace DeploymentData <<Database>> {
        class ComponentDeployment <<ArgoCD Application>>
        ComponentDeployment : GitLocation componentConfiguration
        ComponentDeployment : String namespace

        class NetworkPathConfigDeployment <<ArgoCD Application>>
        NetworkPathConfigDeployment : String namespace

        class Namespace <<k8s manifest>>
        Namespace : String name

        class ExecutionEnvironment <<Directory>>
        ExecutionEnvironment : String path

        class NetworkPath <<Directory>>
        NetworkPath : String path

        class GitDeploymentRepository

        ComponentDeployment --o ExecutionEnvironment 
        ExecutionEnvironment --o GitDeploymentRepository 

        NetworkPathConfigDeployment --o NetworkPath
        NetworkPath --o GitDeploymentRepository

        NetworkPathConfigDeployment -- Namespace
        ComponentDeployment -- Namespace

        "Namespace" --o ExecutionEnvironment
        "Namespace" --o NetworkPath
    } 

    namespace ConfigurationData <<Database>> {
        class ComponentConfiguration <<Subdirectory>>
        ComponentConfiguration : Kustomize manifests
        ComponentConfiguration : GitLocation[] baseConfiguration
        ComponentConfiguration --> ComponentConfiguration : base >

        class ProvidedInterface <<Service or Ingress>>
        ProvidedInterface : String hostname
        ProvidedInterface : String port

        class ConsumedInterface <<ConfigMap>>
        ConsumedInterface : String hostname
        ConsumedInterface : String port
        ConsumedInterface : boolean tls-sni

        class NetworkPathConfiguration <<Subdirectory>>
        NetworkPathConfiguration : Kustomize manifests
        NetworkPathConfiguration : GitLocation[] baseConfiguration
        NetworkPathConfiguration --> NetworkPathConfiguration : base >

        class FirewallConfig <<k8s CustomResource>>

        class ApplicationInstanceOrTemplate <<Directory>>
        ApplicationInstanceOrTemplate : String path

        class GitConfigurationRepository

        ComponentConfiguration --o ApplicationInstanceOrTemplate 
        NetworkPathConfiguration --o ApplicationInstanceOrTemplate 
        FirewallConfig --o NetworkPathConfiguration
        
        ProvidedInterface --o ComponentConfiguration
        ConsumedInterface --o ComponentConfiguration

        ApplicationInstanceOrTemplate --o GitConfigurationRepository

'        note "these are deployment specific -\nshouldn't they be deployment data?" as notedeploymentspecific
'        notedeploymentspecific -- ConsumedInterface
'        notedeploymentspecific -- ProvidedInterface

    }

    Git.DeploymentData.GitDeploymentRepository --|> GitRepository 
    Git.ConfigurationData.GitConfigurationRepository --|> GitRepository
    Git.DeploymentData.ComponentDeployment -- Git.ConfigurationData.ComponentConfiguration : points to >
    Git.DeploymentData.NetworkPathConfigDeployment -- Git.ConfigurationData.NetworkPathConfiguration : points to >

}
@enduml
